#! /usr/bin/env ruby

require 'pg'
require 'bundler/setup'
require 'date'
require 'io/console'

class ExpenseData
  def initialize
    @connection = PG.connect(dbname: 'expenses')
  end

  def add_expense(amount, memo)
    date = Date.today
    sql = "INSERT INTO expenses (amount, memo, created_on) VALUES ($1, $2, $3)"

    @connection.exec_params(sql, [amount, memo, date])
  end

  def delete_expense(id)
    result = @connection.exec_params("SELECT * FROM expenses WHERE id = $1", [id])

    if result.ntuples == 1
      sql = "DELETE FROM expenses WHERE id = $1"
      @connection.exec_params(sql, [id])

      puts "The following expense has been deleted:"
      display_expenses(result)
    else
      puts "There is no expense with id '#{id}'."
    end
  end

  def delete_all_expenses
    @connection.exec("DELETE FROM expenses")
    puts 'All expenses have been deleted.'
  end

  def list_expenses
    result = @connection.exec("SELECT * FROM expenses ORDER BY created_on")

    display_expenses(result)
  end

  def list_select_expenses(term)
    sql = "SELECT * FROM expenses WHERE memo ILIKE $1"
    result = @connection.exec_params(sql, ["%#{term}%"])

    display_expenses(result)
  end

  private

  def display_expenses(tuples)
    tuples.each do |tuple|
      columns = [ tuple['id'].rjust(3),
                  tuple['created_on'].rjust(10),
                  tuple['amount'].rjust(10),
                  tuple['memo'] ]

      puts columns.join(' | ')
    end
  end
end

class CLI
  def initialize
    @application = ExpenseData.new
  end

  def run(arguments)
    command = arguments.first

    case command
    when 'add'
      amount, memo = ARGV[1], ARGV[2]

      abort 'You must provide an amount and memo.' unless amount && memo

      @application.add_expense(amount, memo)
    when 'list'
      @application.list_expenses
    when 'search'
      @application.list_select_expenses(ARGV[1])
    when 'delete'
      @application.delete_expense(ARGV[1])
    when 'clear'
      puts '=> This will remove all expenses, are you sure? (y/n)'
      response = $stdin.getch

      @application.delete_all_expenses if response == 'y'
    else
      puts info
    end
  end

  def info
    <<~INFO
      An expense recording system

      Commands:

      add AMOUNT MEMO - record a new expense
      clear - delete all expenses
      list - list all expenses
      delete NUMBER - remove expense with id NUMBER
      search QUERY - list expenses with a matching memo field
    INFO
  end
end

CLI.new.run(ARGV)
